# Form implementation generated from reading ui file 'VarUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1627, 875)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(50, 30, 75, 23))
        self.start_pushButton.setObjectName("start_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stop_pushButton.setGeometry(QtCore.QRect(50, 60, 75, 23))
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.fps_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.fps_textEdit.setGeometry(QtCore.QRect(290, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fps_textEdit.setFont(font)
        self.fps_textEdit.setObjectName("fps_textEdit")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 120, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.fps_repetition_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.fps_repetition_textEdit.setGeometry(QtCore.QRect(290, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fps_repetition_textEdit.setFont(font)
        self.fps_repetition_textEdit.setObjectName("fps_repetition_textEdit")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(210, 140, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.initFrame_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.initFrame_label.setGeometry(QtCore.QRect(10, 190, 721, 611))
        self.initFrame_label.setAutoFillBackground(True)
        self.initFrame_label.setText("")
        self.initFrame_label.setObjectName("initFrame_label")
        self.checkBox_record_video = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_record_video.setGeometry(QtCore.QRect(240, 20, 131, 23))
        self.checkBox_record_video.setObjectName("checkBox_record_video")
        self.checkBox_plot_video = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_plot_video.setGeometry(QtCore.QRect(240, 50, 131, 23))
        self.checkBox_plot_video.setObjectName("checkBox_plot_video")
        self.brightness_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.brightness_pushButton.setGeometry(QtCore.QRect(620, 70, 121, 23))
        self.brightness_pushButton.setObjectName("brightness_pushButton")
        self.brightness_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.brightness_textEdit.setGeometry(QtCore.QRect(760, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brightness_textEdit.setFont(font)
        self.brightness_textEdit.setObjectName("brightness_textEdit")
        self.contrast_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.contrast_pushButton.setGeometry(QtCore.QRect(620, 100, 121, 23))
        self.contrast_pushButton.setObjectName("contrast_pushButton")
        self.contrast_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.contrast_textEdit.setGeometry(QtCore.QRect(760, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contrast_textEdit.setFont(font)
        self.contrast_textEdit.setObjectName("contrast_textEdit")
        self.initFrame2_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.initFrame2_label.setGeometry(QtCore.QRect(760, 190, 851, 621))
        self.initFrame2_label.setAutoFillBackground(True)
        self.initFrame2_label.setText("")
        self.initFrame2_label.setObjectName("initFrame2_label")
        self.folder_name_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.folder_name_textEdit.setGeometry(QtCore.QRect(500, 20, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.folder_name_textEdit.setFont(font)
        self.folder_name_textEdit.setObjectName("folder_name_textEdit")
        self.checkBox_visualise = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_visualise.setGeometry(QtCore.QRect(240, 80, 131, 23))
        self.checkBox_visualise.setObjectName("checkBox_visualise")
        self.checkBox_from_file = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_from_file.setGeometry(QtCore.QRect(400, 20, 131, 23))
        self.checkBox_from_file.setObjectName("checkBox_from_file")
        self.exp_name_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.exp_name_textEdit.setGeometry(QtCore.QRect(30, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exp_name_textEdit.setFont(font)
        self.exp_name_textEdit.setObjectName("exp_name_textEdit")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 100, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.create_images_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_images_pushButton.setGeometry(QtCore.QRect(1160, 50, 121, 23))
        self.create_images_pushButton.setObjectName("create_images_pushButton")
        self.saturation_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.saturation_textEdit.setGeometry(QtCore.QRect(1040, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saturation_textEdit.setFont(font)
        self.saturation_textEdit.setObjectName("saturation_textEdit")
        self.saturation_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saturation_pushButton.setGeometry(QtCore.QRect(900, 70, 121, 23))
        self.saturation_pushButton.setObjectName("saturation_pushButton")
        self.contrast_textEdit_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.contrast_textEdit_3.setGeometry(QtCore.QRect(1100, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contrast_textEdit_3.setFont(font)
        self.contrast_textEdit_3.setObjectName("contrast_textEdit_3")
        self.contrast_textEdit_4 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.contrast_textEdit_4.setGeometry(QtCore.QRect(1100, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contrast_textEdit_4.setFont(font)
        self.contrast_textEdit_4.setObjectName("contrast_textEdit_4")
        self.gamma_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.gamma_textEdit.setGeometry(QtCore.QRect(1040, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gamma_textEdit.setFont(font)
        self.gamma_textEdit.setObjectName("gamma_textEdit")
        self.gamma_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.gamma_pushButton.setGeometry(QtCore.QRect(900, 110, 121, 23))
        self.gamma_pushButton.setObjectName("gamma_pushButton")
        self.white_balance_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.white_balance_pushButton.setGeometry(QtCore.QRect(900, 150, 121, 23))
        self.white_balance_pushButton.setObjectName("white_balance_pushButton")
        self.white_balance_textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.white_balance_textEdit.setGeometry(QtCore.QRect(1040, 150, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.white_balance_textEdit.setFont(font)
        self.white_balance_textEdit.setObjectName("white_balance_textEdit")
        self.gamma_textEdit_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.gamma_textEdit_3.setGeometry(QtCore.QRect(1100, 150, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gamma_textEdit_3.setFont(font)
        self.gamma_textEdit_3.setObjectName("gamma_textEdit_3")
        self.contrast_textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.contrast_textEdit_2.setGeometry(QtCore.QRect(820, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contrast_textEdit_2.setFont(font)
        self.contrast_textEdit_2.setObjectName("contrast_textEdit_2")
        self.brightness_textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.brightness_textEdit_2.setGeometry(QtCore.QRect(820, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brightness_textEdit_2.setFont(font)
        self.brightness_textEdit_2.setObjectName("brightness_textEdit_2")
        self.file_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.file_pushButton.setGeometry(QtCore.QRect(400, 50, 81, 23))
        self.file_pushButton.setObjectName("file_pushButton")
        self.court_points_L_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.court_points_L_pushButton.setGeometry(QtCore.QRect(400, 80, 161, 23))
        self.court_points_L_pushButton.setObjectName("court_points_L_pushButton")
        self.save_points_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_points_pushButton.setGeometry(QtCore.QRect(400, 140, 161, 23))
        self.save_points_pushButton.setObjectName("save_points_pushButton")
        self.court_points_R_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.court_points_R_pushButton.setGeometry(QtCore.QRect(400, 110, 161, 23))
        self.court_points_R_pushButton.setObjectName("court_points_R_pushButton")
        self.img_size_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.img_size_comboBox.setGeometry(QtCore.QRect(620, 140, 151, 25))
        self.img_size_comboBox.setObjectName("img_size_comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1627, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_pushButton.setText(_translate("MainWindow", "Start"))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.fps_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">60</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "fps input"))
        self.fps_repetition_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">60</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "fps output"))
        self.checkBox_record_video.setText(_translate("MainWindow", "record video"))
        self.checkBox_plot_video.setText(_translate("MainWindow", "plot video"))
        self.brightness_pushButton.setText(_translate("MainWindow", "Brightness"))
        self.brightness_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">50</span></p></body></html>"))
        self.contrast_pushButton.setText(_translate("MainWindow", "Contrast"))
        self.contrast_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">50</span></p></body></html>"))
        self.folder_name_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.checkBox_visualise.setText(_translate("MainWindow", "visualise"))
        self.checkBox_from_file.setText(_translate("MainWindow", "from file"))
        self.exp_name_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">video1</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Exp Name"))
        self.create_images_pushButton.setText(_translate("MainWindow", "Create Images"))
        self.saturation_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">50</span></p></body></html>"))
        self.saturation_pushButton.setText(_translate("MainWindow", "Saturation"))
        self.contrast_textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">70</span></p></body></html>"))
        self.contrast_textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">110</span></p></body></html>"))
        self.gamma_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">50</span></p></body></html>"))
        self.gamma_pushButton.setText(_translate("MainWindow", "Gamma"))
        self.white_balance_pushButton.setText(_translate("MainWindow", "White Balance"))
        self.white_balance_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">50</span></p></body></html>"))
        self.gamma_textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">5000</span></p></body></html>"))
        self.contrast_textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.brightness_textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">0</span></p></body></html>"))
        self.file_pushButton.setText(_translate("MainWindow", "file"))
        self.court_points_L_pushButton.setText(_translate("MainWindow", "court points L"))
        self.save_points_pushButton.setText(_translate("MainWindow", "save points"))
        self.court_points_R_pushButton.setText(_translate("MainWindow", "court points R"))
